# API design (HTTP / JSON)

This project's response helpers, route groups and other implementation details are recorded in [PROJECT.md](./PROJECT.md).

## Paths

| Rule | Example |
| --- | --- |
| One prefix with a version: `/api/v1` | `/api/v1/account/profile` |
| Resources are nouns; words joined with `-`; collections are plural | `/api/v1/invoices`, `/api/v1/credit-transactions` |
| At most two levels of nesting | `/api/v1/notes/:id/export` |
| Actions that no HTTP method expresses use a verb sub-path | `/api/v1/subscription/cancel` |
| Admin endpoints have their own group | `/api/v1/admin/*` |
| Third-party callbacks (webhooks, OAuth) use fixed paths | `/api/v1/stripe/webhook` |

## Methods

| Method | Use | Idempotent |
| --- | --- | --- |
| `GET` | read; no side effects | yes |
| `POST` | create a resource or perform an action | no; use `Idempotency-Key` where needed |
| `PATCH` | partial update | yes |
| `PUT` | full replacement (rare) | yes |
| `DELETE` | delete | yes |

## Request headers

| Header | Purpose |
| --- | --- |
| `Authorization: Bearer <token>` | user identity |
| `Content-Type: application/json` | request bodies are JSON (except file uploads) |
| `X-Request-ID` | optional; sent by the client or generated by the server, and **always returned in the response** |
| `Idempotency-Key` | required for writes with side effects that may be submitted twice |
| `traceparent` | W3C trace context, propagated automatically between services |

## Response shape

The whole API uses one response shape. The recommended envelope:

```json
{ "code": 200, "msg": "ok", "data": { } }
```

- `code` equals the HTTP status code.
- Only endpoints bound to an external protocol (webhooks, file downloads, redirects) may skip the envelope.

## Errors

| HTTP | When |
| --- | --- |
| 400 | invalid parameters or format, or a business rule forbids it |
| 401 | not signed in, or the token is invalid or expired |
| 403 | signed in but not allowed |
| 404 | the resource does not exist. **Another user's resource is also 404**, so existence is not revealed |
| 409 | conflicting state: duplicate creation, version conflict, an idempotency key reused with a different body |
| 422 | (optional) semantic validation failure; choose between 400 and 422 once for the whole project |
| 429 | rate limit exceeded |
| 500 | unknown error; fixed message, no internals |
| 503 | feature disabled or a dependency temporarily unavailable |

### `reason`: a stable error code for programs

When the client must branch on an error, return a stable `reason` in `data`:

```json
{ "code": 400, "msg": "auth: invalid or expired verification code", "data": { "reason": "AUTH_INVALID_CODE" } }
```

- Format `<MODULE>_<CAUSE>`, upper case with underscores; **never changed once released**.
- `msg` is for developers; clients **never show it**. User-facing text comes from the client, based on `reason` and its translations.

### Safety
- 500 responses carry no exception details; failed logins do not reveal whether the user exists.
- Internal details go to the logs only; users report problems with their `X-Request-ID`.

## Data formats

| Type | Rule | Example |
| --- | --- | --- |
| Field names | one style across the project (snake_case recommended) | `created_at` |
| Times | RFC 3339 in **UTC** | `"2026-10-06T03:19:30Z"` |
| **Money** | **integer in the currency's minor unit**, together with the currency | `{"amount": 1999, "currency": "usd"}` |
| IDs | strings | `"8f2c…"` |
| Enums | snake_case strings | `"period_end"` |
| Empty values | a given field is always `null` or always omitted | |

## Pagination, filtering, sorting

```text
GET /api/v1/invoices?page=1&limit=20&status=paid&sort=-created_at
```

```json
{ "code": 200, "msg": "ok", "data": { "items": [], "total": 135, "page": 1, "limit": 20 } }
```

- `page` starts at 1; `limit` defaults to 20, **maximum 100**.
- Sorting is stable (for example `created_at DESC, id DESC`); only indexed fields can be sorted on; `-` means descending.
- Large or live-scrolling lists use cursor pagination (`cursor` / `next_cursor`), documented on the endpoint.
- Search terms use `q`, with a maximum length.

## Idempotency

- Endpoints where **a retry causes damage** (creating orders, granting credits, changing key settings) require `Idempotency-Key`.
- The server stores key → request digest → result: the same key and body return the same result; a different body returns 409.
- Webhooks are de-duplicated by event ID.

## Authentication, rate limiting, CORS

- Authentication happens in a route group or middleware; ownership is **checked again** in the business layer (see [SECURITY_STANDARD.md](./SECURITY_STANDARD.md#authorization)).
- Endpoints prone to abuse (login, verification codes) are rate-limited and return 429.
- CORS allows listed origins only, never `*`.

## Compatibility

- Within a major version, changes are **additive only**: new fields, endpoints and optional parameters.
- Never remove or rename fields, change their type or meaning, or make an optional parameter required.
- When a breaking change is unavoidable, add `/api/v2/...`, keep the old endpoint for at least one release cycle, and return a `Deprecation` header.
- When frontend and backend deploy separately, the in-between state (new backend, old frontend) must work.

## API contracts

- When an endpoint changes, its callers' types (frontend, other services, SDKs) are updated in **the same pull request**.
- OpenAPI is the recommended contract: generate the spec from code, generate client types from it, and have CI check the generated output is current.
